name: imls_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.4
  - plyfile
  - python=3.10.16
  - pip=25.0
  - pytorch=2.4.0
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - tqdm
  - pip:
    - submodules/diffsplatting
    - submodules/dmc
    - submodules/nvdiffrast
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
    - open3d
    - imageio
    - scikit-image
